test:
  stage: test
  tags:
    - php8.1
    - composer
    - npm
    - node.js
  script:
    - composer install
    - npm clean-install
    - npm run build
    - composer test:codeception

  artifacts:
    paths:
      - ./tests/_output/*.fail.html
